name: idf-env
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas=0.10
  - jupyter=1.0
  - notebook=6.4
  - dask=2022.5
  - xarray=2022.3
  - bottleneck=1.3
  - netcdf4=1.5
  - nc-time-axis=1.4
  - holoviews=1.14
  - bokeh=2.4
  - hvplot=0.8
  - geoviews=1.9
  - appmode=0.8
