name: idf-env
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas=0.10.2
  - jupyter=1.0.0
  - notebook=6.4.11
  - dask=2022.5.0
  - xarray=2022.3.0
  - bottleneck=1.3.4
  - netcdf4=1.5.8
  - nc-time-axis=1.4.1
  - holoviews=1.14.9
  - bokeh=2.4.3
  - hvplot=0.8.0
  - geoviews=1.9.5
  - appmode=0.8.0
